server:
  image: 182.140.210.216/minsheng/bookstore
  links:
    - mongo
  environment:
    - MONGO_SERVER=mongo
  ports:
    - "8181"

mongo:
  image: daocloud.io/library/mongo
  ports:
    - "27017:27017"
